### ISSUE TITLE
Cannot select binary or AFL cores

### ISSUE THREAD

**Issue by Pascal-0x90** [wes4m/phuzzerUI#1]
# Issue
Cannot select binary or AFL cores when using the webUI
![image](https://user-images.githubusercontent.com/35417308/86505848-73875780-bd7e-11ea-9a30-4cb0f2853e5d.png)

## Stats
Firefox
Ubuntu
Basic setup described in README.md

**Comment by wes4m** [comment]
Issue was with dropdown css in the style I'm using. Fixed.
